# Cortex — application.conf (SOC Lab)
play.http.secret.key = "cortex-lab-secret-change-in-prod"

search {
  index = cortex
  uri   = "http://elasticsearch:9200"
}

analyzer {
  urls = [
    "/opt/Cortex-Analyzers/analyzers"
  ]
}
responder {
  urls = [
    "/opt/Cortex-Analyzers/responders"
  ]
}

auth {
  provider = [local]
  defaultUserDomain = "soc.lab"
}

job {
  runner = [docker, process]
}
