[soc_indexes]
definition = (index=soc_suricata OR index=soc_endpoints OR index=soc_windows)
iseval = 0

[misp_iocs]
definition = inputlookup misp_iocs.csv
iseval = 0

[mitre_enrich(1)]
args = technique
definition = lookup mitre_attack.csv technique_id AS $technique$ OUTPUT tactic technique_name
iseval = 0
