# =====================================================
#  transforms.conf — extracciones y lookups
# =====================================================

[auth_transforms]
REGEX = (?<status>Failed|Accepted)\s+(?:password|publickey)\s+for(?:\s+invalid user)?\s+(?<user>\S+)\s+from\s+(?<src_ip>\S+)\s+port\s+(?<src_port>\d+)
FORMAT = status::"$1" user::"$2" src_ip::"$3" src_port::"$4"

# ---- Lookups ----
[misp_iocs_lookup]
filename = misp_iocs.csv
case_sensitive_match = false

[threat_actors_lookup]
filename = threat_actors.csv
case_sensitive_match = false

[mitre_attack_lookup]
filename = mitre_attack.csv
case_sensitive_match = false
