%YAML 1.1
---
# Configuración Suricata 7 — SOC Lab
vars:
  address-groups:
    HOME_NET: "[172.30.0.0/24,172.31.0.0/24]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    DC_SERVERS: "$HOME_NET"
  port-groups:
    HTTP_PORTS: "80,8080,8000"
    SHELLCODE_PORTS: "!80"
    SSH_PORTS: "22"
    DNP3_PORTS: "20000"
    MODBUS_PORTS: "502"

default-log-dir: /var/log/suricata/

outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert:
            payload: yes
            payload-printable: yes
            packet: yes
            metadata: yes
            http-body: yes
            tls: yes
        - http:
            extended: yes
        - dns:
            query: yes
            answer: yes
        - tls:
            extended: yes
        - files:
            force-magic: yes
        - ssh
        - flow
        - stats:
            totals: yes

  - fast:
      enabled: yes
      filename: fast.log
      append: yes

af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes

app-layer:
  protocols:
    tls:
      enabled: yes
      detection-ports:
        dp: 443
    http:
      enabled: yes
    ssh:
      enabled: yes
    dns:
      tcp: { enabled: yes, detection-ports: { dp: 53 } }
      udp: { enabled: yes, detection-ports: { dp: 53 } }

default-rule-path: /var/lib/suricata/rules
rule-files:
  - suricata.rules
  - custom.rules

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

logging:
  default-log-level: info
  outputs:
    - console: { enabled: yes }
    - file:
        enabled: yes
        level: info
        filename: /var/log/suricata/suricata.log
