# TheHive 5 — application.conf (SOC Lab)
db.janusgraph {
  storage {
    backend: cql
    hostname: ["cassandra"]
    cql { cluster-name: thp, keyspace: thehive }
  }
  index.search {
    backend: elasticsearch
    hostname: ["elasticsearch"]
    index-name: thehive
  }
}

storage {
  provider: localfs
  localfs.location: /opt/thp/thehive/files
}

application.baseUrl: "http://localhost:9000"

play.http.session.maxAge: 8h
akka.http.parsing.max-content-length: 50M

organisation.default: "SOC-LAB"
user.autoCreateOnSso: true

notification.webhook {
  endpoints = [
    { name = "slack-soc", url = "http://alertmanager:9093/soc" }
  ]
}
